imports:
  - config.base.yaml

system:
  hostname: adam-desktop

disks:
  layout: lvm
  esp:
    device: /dev/nvme1n1
    size: 4GiB
  swap:
    type: swapfile
    size: 64GiB
  lvm:
    vg: vg0
    lv: root
    filesystem: xfs
    pvs:
      - /dev/nvme1n1p2
      - /dev/nvme0n1
      - /dev/nvme2n1

packages:
  - cachyos-v4/nvidia-utils
  - cachyos-v4/lib32-nvidia-utils

hooks:
  - name: Install Nvidia drivers
    at: after:packages
    root: true
    run: chwd --install nvidia-open-dkms
