imports:
  - config.base.yaml

system:
  hostname: adam-desktop

disks:
  layout: lvm
  esp:
    device: /dev/nvme0n1
    size: 4GiB
  swap:
    type: swapfile
    size: 64GiB
  lvm:
    vg: vg0
    lv: root
    filesystem: xfs
    pvs:
      - /dev/nvme0n1p2
      - /dev/nvme1n1

hooks:
  - name: Install Nvidia drivers
    at: post-bootstrap
    root: true
    run: chwd --install nvidia-open-dkms
