# vim:set ft=tmux:
%hidden MODULE_NAME="time"
set -ogq "@catppuccin_${MODULE_NAME}_icon" "󰭦 "
set -ogqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_sky}"
set -ogq "@catppuccin_status_${MODULE_NAME}_text_fg" "#{E:@thm_fg}"
set -ogq "@catppuccin_status_${MODULE_NAME}_text_bg" "#{E:@thm_bg}"
set -ogq "@catppuccin_${MODULE_NAME}_text" " %Y-%m-%d 󰅐 %I:%M %p"

source -F "#{d:current_file}/../plugins/tmux/utils/status_module.conf"
